# Autogenerated wrapper script for acados_jll for x86_64-apple-darwin-march+avx2
export acados_solver_template, libacados

using blasfeo_jll
using hpipm_jll
JLLWrappers.@generate_wrapper_header("acados")
JLLWrappers.@declare_file_product(acados_solver_template)
JLLWrappers.@declare_library_product(libacados, "@rpath/libacados.dylib")
function __init__()
    JLLWrappers.@generate_init_header(blasfeo_jll, hpipm_jll)
    JLLWrappers.@init_file_product(
        acados_solver_template,
        "share/acados/c_templates_tera/acados_solver.in.c",
    )

    JLLWrappers.@init_library_product(
        libacados,
        "lib/libacados.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
